version: '3'

services:
  jscam:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /home/project/src/jscam
    image: jscam
    stdin_open: true
    tty: true
    #entrypoint: /my_entrypoint.sh
    network_mode: "host"
    privileged: false
    volumes:
     - "../src/jscam:/home/project/src/jscam"
     - "./node_modules:/home/project/src/jscam/node_modules"
     - "/etc/group:/etc/group:ro"
     - "/etc/sudoers:/etc/sudoers:ro"
     - "/etc/shadow:/etc/shadow:ro"
     - "/etc/passwd:/etc/passwd:ro"
     - "/tmp/.X11-unix:/tmp/.X11-unix"

