FROM debian:jessie

ENV ANDROID_COMPILE_SDK "23"
ENV ANDROID_BUILD_TOOLS "23.0.1"
#ENV ANDROID_SDK_TOOLS "26.1.1"
#ENV SDK_LINK https://dl.google.com/android/android-sdk_r${ANDROID_SDK_TOOLS}-linux.tgz
ENV SDK_LINK "https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip"
ENV SDK_HASH "444e22ce8ca0f67353bda4b85175ed3731cae3ffa695ca18119cbacef1c1bea0"

ENV ANDROID_HOME=$PWD/android-sdk-linux
ENV PATH=$PATH:$PWD/android-sdk-linux/platform-tools/

RUN apt-get update && apt-get install -y curl

RUN echo 'deb http://http.debian.net/debian jessie-backports main' >> /etc/apt/sources.list
RUN curl -sL https://deb.nodesource.com/setup_9.x -o nodesource_setup.sh && \
    bash nodesource_setup.sh

RUN apt-get update
RUN apt-get install -t jessie-backports -y openjdk-8-jdk
RUN apt-get install -y nodejs \
                       git \
                       sudo \
                       wget \
                       tar \
                       unzip \
                       lib32stdc++6 \
                       lib32z1 \
    && apt-get clean

RUN npm install -g react-native-cli yarn

#CMAKE INSTALLATION (android sdk has older versions, but if you need newer...)
#RUN git clone https://github.com/Kitware/CMake \
#    && cd CMake && ./bootstrap && make && make install \
#    && cd .. && rm -rf CMake


#RUN yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses &&            \
#    $ANDROID_HOME/tools/bin/sdkmanager  "build-tools;23.0.2"          \
#                                        "build-tools;25.0.2"          \
#                                        "cmake;3.6.4111459"           \
#                                        "ndk-bundle"                  \
#                                        "platform-tools"              \
#                                        "platforms;android-23"        \
#                                        "build-tools;23.0.1"          \
#                                        "build-tools;26.0.1"          \
#                                        "build-tools;26.0.2"          \
#                                        "extras;android;m2repository" \
#                                        "extras;google;m2repository"  \
#                                        "ndk-bundle"                  \
#                                        --verbose 

ENV ANDROID_NDK $ANDROID_HOME/ndk-bundle
ENV ANDROID_NDK_HOME $ANDROID_NDK
